### ISSUE TITLE
Main/Live/Buttons

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#16]
As a user, I want buttons on the main page, so that I can get more information about live events.

***

**Acceptance Criteria**

- A placeholder button for booking tickets regarding live events.
- A placeholder button for more information about all live events.
- Correct structure & styling to match rest of the main page.

***

**Tasks**
 
- [x] Develop HTML code for structure.
- [x] Style to match the main page.
- [x] Test responsive layout for desktop and mobile devices.

 How it should look

![Image](https://github.com/user-attachments/assets/bfcba2ce-ce37-4dab-b77c-cd1daecbc961)

***

**Is this tested?**
 

- [ ] Yes
