### ISSUE TITLE
Main/Header/Navigation Bar

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#17]
### User Story
As a user, I want to easily navigate through the website/app using a clear, functional, and responsive navigation bar, so that I can access important sections without difficulty.

### Acceptance Criteria

- Menu items include: Biljetter, Evenemang, Filmer, Medlemskap, and Om oss.
- The navigation bar is responsive, with a dropdown menu for mobile and tablet views (more info about the mobile burger menu in another card)
- Hover effects are implemented for menu items, with a clear visual indicator.

### Tasks

- [x] Design the navigation bar (UI design, colors, icons, layout).
- [x] Create HTML structure for the navigation bar.
- [x] Implement CSS styles to match the design (colors, fonts, layout).
- [x] Implement responsive behaviour (media queries for mobile and tablet views).

### Is this tested?

- [ ] Yes
