### ISSUE TITLE
Main/Movie/Features

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#18]
### User Story
**As a user**
**I want** to see a header and buttons displaying what section of the page I am on,
**So that** I can easily navigate that category.

### Acceptance Criteria

- A header should be shown letting the user know which section/category of the page they are on (e.g. Filmer på Kino).
- Two buttons should be shown beneath the movie cards letting the user continue to either "Boka biljett" or "Se alla filmer".
- The style should be similar to [the one on Whimsical.](https://whimsical.com/BwPBdCtcLYJvtFNMcYbLvm)

### Tasks

- [ ] Style the header so it appears like on Whimsical.
- [ ] Style the buttons so they appear like on Whimsical.
- [ ] Add placeholder links for the buttons that will in the future be connected to respective pages.

### Is this tested?

- [ ] Yes
