### ISSUE TITLE
Main/mobile/burgerMenu

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#20]
### User Story
**As a user** - when im on my phone i want to be able to use a phone friendly menu
**I want**
**So that** - 

### Acceptance Criteria

- while on a phone there should be a burger menu that i can access while on the site.

### Tasks

- [x] add a burger icon in the top right corner
- [x] add functionality to open and close burger meny
- [x] add nav links to menu

_____

![Image](https://github.com/user-attachments/assets/34c1c4d8-01e2-4c38-aa90-9d34e0d81f44)
