### ISSUE TITLE
Main/story part/catchphrase

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#28]
**User story:**
As a user, I want to see a catchphrase so that I can understand the value of the movie theater. 

**Acceptance Criteria:**
- The catchphrase needs to be clearly visible.
- Styled to stand out, with a bigger font. 
- The supporting text should be smaller. 
- The colors should follow the style guide. 
- The section should be responsive.

**Tasks:**
- [x] Create the HTML structure for the catchphrase section.
- [x] Use proper HTML elements, such as h1 for the main catchphrase, to ensure the section is semantically structured.
- [x] Apply CSS to style the catchphrase and the section. See Whimsical.

![Image](https://github.com/user-attachments/assets/2951acb4-e80c-43bd-92a7-3176a5cf4eab)

**Tested?**
- [ ] Yes
