### ISSUE TITLE
Movies page/Feature/New page

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#29]
### User Story
**As a user**
**I want to see a second page where we can display a list of movies and other features**
**So that the website to be well filled and easy to navigate**

### Acceptance Criteria

- The design is similar to the main page
- The main page and navigation menus should have buttons that will eventually be linked to the second page

### Tasks

- [x]  Create a new page
- [x]  Copy the design from the main page
- [x]  Create a new section in the nav bar and footer if needed
- [x]  Update the vite.config.js file with the new page information

-How it should look in concept

> ![Image](https://github.com/user-attachments/assets/fde30e19-cd00-4dd1-a13e-ce289636b17a)

### Is this tested?

- [x] Yes
