### ISSUE TITLE
Movies page/Feature/Show all movies

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#30]
### User Story
**As a user**
**I want to see all the movies on the second page**
**So that I can spend some more time browsing and looking for movies that interest me.**

### Acceptance Criteria

- The design is similar to the one displayed under tasks.
- All information is fetching from API

### Tasks

- [x]  Fetch movies from API
- [x]  Create a function that displays all movies on page
- [x]  Show all movies on page

- [x] How it should look in concept

> ![Image](https://github.com/user-attachments/assets/b3a71c32-8d41-4974-ab75-70eb7b332478)

### Is this tested?

- [x] Yes
