### ISSUE TITLE
Movies page/New button/Today

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#31]
### User Story
**As a user**
**I want to see a filter that switches between all movies and movies that are showing today**
**So that I can choose a movie for today**

### Acceptance Criteria

- The button design is similar to the one displayed under tasks.
- The list is being updated locally in the browser

### Tasks

- [ ]  Create a new button
- [ ]  Create a function that filters a list of movies
- [ ]  Connect the button to a function

How it should look in concept

> ![Image](https://github.com/user-attachments/assets/b2a02578-928e-4597-99c5-9b92c281257a)

### Is this tested?

- [ ] Yes
