### ISSUE TITLE
Movies page/New button/Popular

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#32]
### User Story
**As a user**
**I want to see a filter that switches between all movies and popular movies**
**So that I can make choose easier**

### Acceptance Criteria

- The button design is similar to the one displayed under tasks.
- The list is being updated locally in the browser

### Tasks

- [ ]  Create a new button
- [ ]  Create a function that gets movie ratings from the API and sorts the movies list
- [ ]  Connect the button to a function

How it should look in concept

> ![Image](https://github.com/user-attachments/assets/7cb31415-b7d6-4e6c-858d-80b1ac8e07d1)

### Is this tested?

- [ ] Yes
