### ISSUE TITLE
Movies page/Feature/Search

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#33]
### User Story
**As a user**
**I want to search for movies**
**So that I can find the movie I am looking for**

### Acceptance Criteria

- The search input field is big and easy to locate
- The list is being updated locally in the browser

### Tasks

- [x]  Create a new title and input field on the All Movies page
- [x]  Create a function that checks the input field and compares it with the movie names from the API
- [x]  Create an event listener that prints a sorted list

How it should look in concept

> ![Image](https://github.com/user-attachments/assets/1c0d2cf9-2a21-42e8-a64b-71ab2a797382)

### Is this tested?

- [x] Yes
