### ISSUE TITLE
Update logo for local cinema

### ISSUE THREAD

**Issue by jennymakki** [Klumpish/kino-bio-projekt#39]
##User Story
As a user, I want to get a clear visual of where the theater is located so that I can visit it.

## Acceptance Criteria
- The updated logo file should be provided in the required format.
- The logo should be updated in all locations where the previous logo was used

## Tasks

- [ ] Obtain updated logo
- [ ] Update logo in website Header
- [ ] Test mobile responsiveness. 

##Image

![Image](https://github.com/user-attachments/assets/b00b2e9a-1e8d-4ccb-9e67-4a4a6be16cda)

##Is this tested?

- [ ]
