### ISSUE TITLE
feat(api): create data file fetching API

### ISSUE THREAD

**Issue by Kirill9m** [Klumpish/kino-bio-projekt#5]
# Description:

Connect our repo to API Render.com for deployment.

# Tasks

- [ ] create a new branch
- [ ] create a loading(server.js) file for Express.js
- [ ] connect our github repo to Render
- [ ] create a new web service
- [ ] test and run service (node server.js to run)
- [ ] merge the branch
- [ ] change settings on render.com to main branch

Once completed, the API will be deployed on Render.com and accessible to users as required.
